# Generated by Django 5.0.6 on 2024-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0002_article_remove_rental_car_remove_rental_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
