# Generated by Django 5.0.6 on 2024-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0004_article_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(default='non-keyword', max_length=50),
        ),
    ]
