# Generated by Django 5.0.6 on 2024-05-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0005_alter_article_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='heading',
            field=models.TextField(default='non-titled', max_length=50),
        ),
    ]
